Repository stackitcloud/gardener, pull requests merged in 2024-04, with the labels that each got.

#62 add hown3d and Duciwuci to OWNERS
  OWNERS_ALIASES
Labels: size/XS, kind/enhancement, approved, lgtm

#65 Fix fetching CA bundle secret in DWD migration function (#9276)
  cmd/gardenlet/app/app.go
  pkg/component/dependencywatchdog/access.go
Labels: size/M, approved, lgtm, tide/merge-method-rebase, kind/bug

#64 Always update resource manager
  VERSION
  pkg/component/shared/resourcemanager.go
Labels: size/XS, kind/enhancement, approved, lgtm, tide/merge-method-rebase
