Repository stackitcloud/gardener, pull requests merged in 2024-09, with the labels that each got.

#98 `test-integration` should depend on `$(HELM)`
  Makefile
Labels: size/XS, approved, lgtm, kind/bug

#99 Adopt OWNERS_ALIASES for v1.97
  OWNERS_ALIASES
Labels: size/M, kind/enhancement, approved, lgtm

#100 Allow changing backup provider to S3
  pkg/apis/core/validation/backupbucket.go
  pkg/apis/core/validation/seed.go
  pkg/apis/extensions/validation/backupbucket.go
  pkg/apis/extensions/validation/backupentry.go
Labels: size/S, kind/enhancement, approved, lgtm

#101 cherry pick of: Allow changing backup provider to S3 (#100)
  pkg/apis/core/validation/backupbucket.go
  pkg/apis/core/validation/seed.go
  pkg/apis/extensions/validation/backupbucket.go
  pkg/apis/extensions/validation/backupentry.go
Labels: size/S, kind/enhancement, approved, lgtm, tide/merge-method-rebase
