Repository stackitcloud/gardener, pull requests merged in 2024-02, with the labels that each got.

#37 Fix(controller-manager) Change shoot maintenance controller to use DeepCopy objects for dryRun
  VERSION
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
Labels: size/XS, approved, lgtm, kind/bug

#38 Fix(controller-manager) Change shoot maintenance controller to use De…
  VERSION
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
Labels: size/XS, approved, lgtm, kind/bug

#40 Remove Dependency of OperatingSystemConfig on Extensions
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: size/XS, approved, lgtm, kind/bug

#41 update VERSION
  VERSION
Labels: size/XS, approved, lgtm, kind/bug

#43 Remove vali check for Seed Health
  pkg/operation/care/seed_health.go
Labels: size/XS, approved, lgtm, kind/bug

#44 Add maboehm
  OWNERS_ALIASES
Labels: size/XS, kind/enhancement, approved, lgtm

#46 Ske v1.79 cherry picks
  VERSION
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  pkg/component/coredns/coredns.go
  pkg/component/coredns/mock/mocks.go
  pkg/component/kubeapiserver/kube_apiserver.go
  pkg/component/kubeapiserver/mock/mocks.go
  pkg/component/logging/fluentoperator/fluent_bit_test.go
  pkg/component/logging/fluentoperator/fluent_operator.go
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/component/vpnseedserver/mock/mocks.go
  pkg/component/vpnseedserver/vpn_seed_server.go
  pkg/gardenlet/controller/seed/care/health.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/coredns.go
  pkg/operation/botanist/coredns_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/vpnseedserver.go
  pkg/operation/botanist/vpnseedserver_test.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/types_etcd.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/lease.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/statefulset.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/store.go
  vendor/modules.txt
Labels: size/L, kind/enhancement, approved, lgtm
