Repository stackitcloud/gardener, pull requests merged in 2024-03, with the labels that each got.

#48 resourcemanager: do not fail if hvpa CRD is not deployed
  pkg/resourcemanager/controller/managedresource/reconciler.go
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  third_party/controller-runtime/pkg/apiutil/lazyrestmapper.go
Labels: size/S, approved, lgtm, kind/bug

#49 Update version file
  VERSION
Labels: size/XS, approved, lgtm, kind/bug

#51 Fix unrecoverable issues with `etcd` during credentials rotation (#8795)
  pkg/component/etcd/etcd.go
  pkg/component/etcd/etcd_test.go
  pkg/operation/botanist/etcd.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
Labels: size/M, kind/enhancement, approved, lgtm, tide/merge-method-rebase
