Repository stackitcloud/gardener, pull requests merged in 2024-10, with the labels that each got.

#102 Allow to change `seedSpec.backup.region` for STACKIT:X region migration
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
Labels: size/S, kind/enhancement, approved, lgtm

#106 Allow to change `seedSpec.backup.region` for STACKIT:X region migration
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
Labels: size/S, kind/enhancement, approved, lgtm, tide/merge-method-rebase

#109 Set `insecure_skip_verify` to true for cadvisor and kubelet job
  pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/cadvisor.yaml
  pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/kubelet.yaml
  pkg/component/observability/monitoring/prometheus/cache/scrapeconfigs_test.go
Labels: size/XS, approved, lgtm, kind/bug
