Repository stackitcloud/gardener, pull requests merged in 2024-07, with the labels that each got.

#80 upgrade etcd-druid to `v0.22.0`
  go.mod
  go.sum
Labels: size/XS, kind/enhancement, approved, lgtm

#83 Allow changing the project creator of the "garden" project
  pkg/apis/core/validation/project.go
Labels: size/XS, kind/enhancement, approved, lgtm

#84 [v1.90] Omit useless data from `OperatingSystemConfig` in `Secret`s reconciled by `gardener-node-agent` (#9723)
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets_test.go
Labels: size/M, approved, lgtm, tide/merge-method-rebase, kind/bug

#85 [v1.91] Omit useless data from `OperatingSystemConfig` in `Secret`s reconciled by `gardener-node-agent` (#9723)
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets_test.go
Labels: size/M, approved, lgtm, tide/merge-method-rebase, kind/bug

#88 add Lukas J. and Florian as new owners
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, kind/task
