Repository stackitcloud/gardener, pull requests merged in 2025-02, with the labels that each got.

#122 Workaround: Gardener Node Agent deletes containerd drop-in
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: size/M, approved, lgtm, tide/merge-method-rebase, kind/bug

#124 Allow configuring a maximum node count per shoot
  docs/README.md
  docs/api-reference/core.md
  docs/usage/shoot/shoot_limits.md
  example/30-cloudprofile.yaml
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
  pkg/gardenlet/operation/botanist/clusterautoscaler.go
  pkg/gardenlet/operation/botanist/clusterautoscaler_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, approved, lgtm, size/XXL

#125 Drop usage of ext-authz-server
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
  pkg/component/networking/istio/test_charts/ingress_vpn_envoy_filter.yaml
Labels: size/L, kind/enhancement, approved, lgtm

#130 `V1.112.2` rebase
  VERSION
  go.mod
  go.sum
  imagevector/containers.yaml
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/controllermanager_test.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: size/M, kind/enhancement, approved, lgtm, tide/merge-method-rebase

#131 Rebase Patch `v1.112.3`
  VERSION
  cmd/gardener-controller-manager/app/app.go
  cmd/gardenlet/app/app.go
  docs/concepts/apiserver-admission-plugins.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apiserver/registry/core/backupentry/strategy_test.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/component/extensions/extension/extension.go
  pkg/utils/gardener/identity_test.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/seed/mutator/admission_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: size/L, kind/enhancement, approved, lgtm
